// Textes pour chaque thème
export const themeTexts = {
    warcraft: {
        title: '⚔ ZogChat ⚔',
        subtitle: 'Communication Mystique entre Royaumes',
        section1: '📜 Votre Sceau Mystique',
        section2: '🏰 Établir une Alliance',
        section3: '⚜ Parchemin des Messages',
        section4: '📖 Codex des Alliances',
        copyBtn: '📜 Graver le Sceau',
        connectBtn: 'Forger l\'Alliance',
        sendBtn: 'Envoyer le Corbeau',
        statusDisconnected: '🏰 Royaume isolé',
        statusWaiting: '⏳ En attente d\'un allié...',
        statusConnected: '⚔ Alliance forgée avec: ',
        statusBroken: '💀 Alliance rompue',
        statusPortal: '🔮 Invocation du portail...',
        peerIdInit: 'Invocation du sceau...',
        connectPlaceholder: 'Inscrivez le sceau de votre allié...',
        messagePlaceholder: 'Rédigez votre missive...',
        chatWaiting: 'Forgez une alliance pour échanger des missives',
        alertCopy: 'Sceau gravé dans les archives !',
        alertNoPeer: 'Inscrivez le sceau de votre allié !',
        alertNotReady: 'Le rituel n\'est pas prêt !',
        instructions: [
            'Gravez votre sceau mystique et transmettez-le à votre allié',
            'Recueillez le sceau de votre allié dans le champ sacré',
            'Forgez l\'alliance en activant le rituel',
            'Échangez vos missives à travers les royaumes !'
        ]
    },
    onepiece: {
        title: '🏴‍☠️ ZogChat 🏴‍☠️',
        subtitle: 'Communication des Pirates du Grand Line',
        section1: '🗺️ Votre Log Pose',
        section2: '⚓ Établir une Route',
        section3: '📨 Journal de Bord',
        section4: '📜 Code des Pirates',
        copyBtn: '🗺️ Copier le Log',
        connectBtn: 'Hisser les Voiles',
        sendBtn: 'Envoyer par Den Den Mushi',
        statusDisconnected: '🏝️ Île isolée',
        statusWaiting: '🌊 Navigation en cours...',
        statusConnected: '⚓ Route établie avec: ',
        statusBroken: '☠️ Connexion perdue en mer',
        statusPortal: '🧭 Calcul de la route...',
        peerIdInit: 'Calibrage du Log Pose...',
        connectPlaceholder: 'Entrez le Log Pose du nakama...',
        messagePlaceholder: 'Écrivez votre message...',
        chatWaiting: 'Établissez une route pour communiquer',
        alertCopy: 'Log Pose copié dans le journal !',
        alertNoPeer: 'Entrez le Log Pose du nakama !',
        alertNotReady: 'Le Log Pose n\'est pas prêt !',
        instructions: [
            'Copiez votre Log Pose et partagez-le avec votre nakama',
            'Récupérez le Log Pose de votre nakama',
            'Hissez les voiles pour établir la connexion',
            'Communiquez à travers le Grand Line !'
        ]
    },
    neon: {
        title: '◆ ZogChat ◆',
        subtitle: 'Réseau de Communication Cyberpunk',
        section1: '🔐 Votre ID Crypté',
        section2: '🌐 Connexion P2P',
        section3: '💬 Terminal de Messages',
        section4: '📡 Protocole',
        copyBtn: '📋 Copier l\'ID',
        connectBtn: 'Initialiser Connexion',
        sendBtn: 'Transmettre',
        statusDisconnected: '🔴 Hors ligne',
        statusWaiting: '🟡 En attente...',
        statusConnected: '🟢 Connecté à: ',
        statusBroken: '❌ Connexion terminée',
        statusPortal: '🔄 Établissement du tunnel...',
        peerIdInit: 'Génération de l\'ID...',
        connectPlaceholder: 'Entrez l\'ID du contact...',
        messagePlaceholder: 'Tapez votre message...',
        chatWaiting: 'Initialisez une connexion pour commencer',
        alertCopy: 'ID copié dans le presse-papier !',
        alertNoPeer: 'Entrez l\'ID du contact !',
        alertNotReady: 'Le système n\'est pas prêt !',
        instructions: [
            'Copiez votre ID crypté et transmettez-le',
            'Récupérez l\'ID de votre contact',
            'Initialisez la connexion P2P sécurisée',
            'Échangez des données en temps réel !'
        ]
    }
};
